language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
services:
  - mysql
  - docker
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS clients_lifetime;'
install:
  - pip install -r requirements.txt
# command to run tests
script: python tests.py
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - docker login -e bgdnvdmtry@yandex.ru -u bgdnvdmtry2 -p BaNaN0973561
  - export REPO=bgdnvdmtry2/clients_timelife
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO