sudo: "required"
language: python
python:
  - "3.6"
services:
  - mysql
  - docker
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS clients_lifetime;'
  - mysql -e 'CREATE TABLE IF NOT EXISTS clients_lifetime.portal_auth (portal CHAR(255) NOT NULL,
  access_token CHAR(255) NOT NULL, refresh_token CHAR(255) NOT NULL, event_counter INT, PRIMARY KEY (portal));'
install:
  - pip install -r requirements.txt
script: python tests.py
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - docker login -u 'bgdnvdmtry2' -p 'BaNaN0973561'
  - docker build -f Dockerfile .
  - docker push bgdnvdmtry2/clients_timelife
  - python app.py