sudo: "required"
language: python
python:
  - "3.6"
# command to install dependencies
services:
  - mysql
  - docker
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS clients_lifetime;'
install:
  - pip install -r requirements.txt
# command to run tests
script: python tests.py
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - docker login -u 'bgdnvdmtry2' -p 'BaNaN0973561'
  - docker build -f Dockerfile .
  - docker push bgdnvdmtry2/clients_timelife
  - python app.py